"""
Utils package initialization.
"""

from utils.time import (
    now,
    today,
    yesterday,
    get_effective_date,
    is_within_grace_period,
    get_streak_deadline,
    time_until_deadline,
    format_time_remaining,
    days_between,
    is_consecutive_day,
    is_same_day,
    get_week_start,
    get_week_dates,
    get_last_n_days,
    get_daily_thread_name,
    get_readable_date,
    get_streak_status_emoji,
    should_send_reminder,
    format_datetime,
)

from utils.json_safe import (
    safe_json_loads,
    safe_json_dumps,
    clean_json_string,
    extract_json_from_text,
    merge_dicts,
    validate_state_structure,
    truncate_for_embed,
    safe_get,
    safe_set,
    compress_for_storage,
    decompress_from_storage,
    calculate_json_size,
    fits_in_embed,
)

from utils.text_analysis import (
    qualifies_as_log,
    calculate_similarity,
    is_duplicate_content,
    detect_technical_depth,
    classify_topic,
    extract_concepts,
    update_concept_frequency,
    calculate_concept_repetition_penalty,
    summarize_logs,
    count_words,
    clean_message_content,
    format_concepts_display,
    analyze_message,
)

__all__ = [
    # Time utilities
    "now",
    "today",
    "yesterday",
    "get_effective_date",
    "is_within_grace_period",
    "get_streak_deadline",
    "time_until_deadline",
    "format_time_remaining",
    "days_between",
    "is_consecutive_day",
    "is_same_day",
    "get_week_start",
    "get_week_dates",
    "get_last_n_days",
    "get_daily_thread_name",
    "get_readable_date",
    "get_streak_status_emoji",
    "should_send_reminder",
    "format_datetime",
    # JSON utilities
    "safe_json_loads",
    "safe_json_dumps",
    "clean_json_string",
    "extract_json_from_text",
    "merge_dicts",
    "validate_state_structure",
    "truncate_for_embed",
    "safe_get",
    "safe_set",
    "compress_for_storage",
    "decompress_from_storage",
    "calculate_json_size",
    "fits_in_embed",
    # Text analysis
    "qualifies_as_log",
    "calculate_similarity",
    "is_duplicate_content",
    "detect_technical_depth",
    "classify_topic",
    "extract_concepts",
    "update_concept_frequency",
    "calculate_concept_repetition_penalty",
    "summarize_logs",
    "count_words",
    "clean_message_content",
    "format_concepts_display",
    "analyze_message",
]
